security:
    password_hashers:
        App\Entity\Eleitor:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN: ROLE_ELEITOR

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Eleitor
                property: tituloEleitor

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt)
            security: false

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                success_handler: App\Security\LoginSuccessHandler

            logout:
                path: app_logout
                target: app_login
                enable_csrf: true

            login_throttling:
                max_attempts: 5
                interval: '1 minute'

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin(?:/|$), roles: ROLE_ADMIN }
        - { path: ^/api/, roles: ROLE_ELEITOR }
        - { path: ^/logout$, roles: ROLE_ELEITOR }
        - { path: ^/$, roles: ROLE_ELEITOR }